image: node:10

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - set -x && apt-get update && apt-get install -y google-chrome-stable
          - yarn
          - yarn test
